name: otm-inventory

# Use postgres/example user/password credentials

services:
  db_pool:
    container_name: db_pool
    image: ${PGBOUNCER_IMG}
    restart: always
    ports:
      - 5432:5432
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_NAME: ${POSTGRES_DB}
      DB_PASSWORD: ${POSTGRES_PASS}
      DB_HOST: db
    depends_on:
      - db
  db:
    container_name: db
    image: ${POSTGRES_IMG}
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}

  adminer:
    container_name: adminer
    image: ${ADMINER_IMG}
    restart: always
    ports:
      - 8080:8080

  redis:
    container_name: redis
    image: ${REDIS_IMG}
    restart: always
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  caddy:
    container_name: caddy
    image: ${CADDY_IMG}
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ../infra/Caddyfile:/etc/caddy/Caddyfile:ro
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:
